FROM rust:1.71-slim as build

WORKDIR /app

COPY ./jwt-lib/ ../jwt-lib/
COPY ./axum-auth/ .

RUN cargo build --release

FROM rust:1.71-slim

WORKDIR /usr/local/bin

COPY --from=build /app/target/release/axum-auth .

EXPOSE 2323

CMD ["./axum-auth"]
